src/utils.rs

The name of the socket has changed from kpxc_server to org.keepassxc.KeePassXC.BrowserServer.
See https://github.com/keepassxreboot/keepassxc/pull/4680/files#diff-071572095d5d87a566ebab7767193a6fR38

socket name for keepassxc 2.6

---

src/config.rs

When running `git-credential-keepassxc configure` for the first
time on a unix system, the newly created config file
`~/.config/git-credential-keepassxc` has the file permissions
`u+rw g+rw o+r`. This is a bit to generous.
This commit restricts the permissions to `u+rw` or 0o600 for unix systems.

Restricting the config permissions to u+rw

---

src/main.rs

It's really hard to use this in scripts otherwise.

exit code != 0 on error

---

.github/workflows/release.yml
.github/workflows/rust.yml
Justfile
src/config.rs

The be honest this is a bit of a minimal effort PR.
After cloning the repo the first things I did were
```
cargo build
cargo test
```
It would be nice if `cargo test` would work without errors and warnings. Currently some tests fail if the `yubikey` feature is not enabled.

Support running tests without yubikey feature

---

.github/workflows/release.yml
.github/workflows/rust.yml
Justfile
src/utils.rs

Add clog output to GitHub release description. Also a new `just release`
command to help with the release process.
Got this on nightly. See [1].
[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
Also don't update CHANGELOG.md if it's a prerelease.

Adopt conventional commits

---

Cargo.lock
Cargo.toml

It was fixed in [1]. And notify-rust introduced this fix in [2].
[1] https://github.com/microsoft/windows-rs/commit/afe32525c22209aa8f632a0f4ad607863b51796a
[2] https://github.com/hoodie/notify-rust/issues/148#event-7434157568
No.

fix: Address windows crate vulnerability

---

.github/workflows/release.yml
.github/workflows/rust.yml

Build macOS universal binaries for x86_64 and aarch64.
No.

build: macOS universal binary in GitHub Actions

---

Cargo.lock
Cargo.toml
src/config.rs
src/utils.rs

aho-corasick v0.7.18 -> v0.7.19
anyhow v1.0.57 -> v1.0.65
async-broadcast v0.4.0 -> v0.4.1
async-channel v1.6.1 -> v1.7.1
async-io v1.7.0 -> v1.9.0
async-task v4.2.0 -> v4.3.0
async-trait v0.1.56 -> v0.1.57
block-buffer v0.10.2 -> v0.10.3
chacha20 v0.8.1 -> v0.8.2
chacha20poly1305 v0.9.0 -> v0.9.1
clap v3.2.4 -> v3.2.22
clap_derive v3.2.4 -> v3.2.18
clap_lex v0.2.2 -> v0.2.4
concurrent-queue v1.2.2 -> v1.2.4
cpufeatures v0.2.2 -> v0.2.5
crossbeam-channel v0.5.4 -> v0.5.6
crossbeam-deque v0.8.1 -> v0.8.2
crossbeam-epoch v0.9.8 -> v0.9.10
crossbeam-utils v0.8.8 -> v0.8.11
crypto-common v0.1.3 -> v0.1.6
digest v0.10.3 -> v0.10.5
either v1.6.1 -> v1.8.0
event-listener v2.5.2 -> v2.5.3
fastrand v1.7.0 -> v1.8.0
futures-core v0.3.21 -> v0.3.24
futures-io v0.3.21 -> v0.3.24
futures-sink v0.3.21 …

chore: Upgrade deps

---

README.md

docs: Use KPH attribute to avoid being overwritten

---

.github/workflows/release.yml
.github/workflows/rust.yml

[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
No

ci: Replace Actions set-output with $GITHUB_OUTPUT

---

.github/workflows/release.yml
.github/workflows/rust.yml
src/config.rs
src/keepassxc/messages/structs.rs
src/main.rs
src/utils.rs

[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
CI was failing as it tried to install libdbus-dev 1.12.16-2ubuntu2.2,
which doesn't exist in Azure's mirror (guess they had a hiccup when
synchronising).
These Linux dependencies were migrated from Travis CI and actually don't
need to be explicitly installed in GitHub Actions.
No

style: Address new needless borrow warnings

---

src/main.rs
src/utils.rs
src/utils/socket.rs

Fixes #53
Breaks down the very convoluted get_socket_path() into smaller pieces,
each taking care of a specific OS and KeePassXC (or KeePass 2)
combination.
Also instead of using a OnceCell to cater for the command line argument,
pass it along using an environment variable. There is no need to cache
this result anyway since it's only called by get_stream(). This should
fall into place nicely in terms of their priority as well.
To avoiding mounting everything into Flatpak sandbox, the socket was
moved into a separate path under Linux [1][2].
Note this does not affect other distributions under Linux as there is a
symbolic link from the old path [3].
[1] https://github.com/keepassxreboot/keepassxc/pull/8030
[2] https://github.com/keepassxreboot/keepassxc/commit/1009650b5c2697f5420c0f439827165 …

Refactor get_socket_path() and support KPXC 2.7.4 for Flatpak

---

Cargo.lock

aes v0.8.1 -> v0.8.2
anyhow v1.0.65 -> v1.0.66
async-io v1.9.0 -> v1.10.0
async-lock v2.5.0 -> v2.6.0
async-trait v0.1.57 -> v0.1.58
base64 v0.13.0 -> v0.13.1
cc v1.0.73 -> v1.0.74
clap v3.2.22 -> v3.2.23
crossbeam-epoch v0.9.10 -> v0.9.11
crossbeam-utils v0.8.11 -> v0.8.12
crypto_box v0.8.1 -> v0.8.2
ctr v0.9.1 -> v0.9.2
fragile v1.2.1 -> v2.0.0
futures-core v0.3.24 -> v0.3.25
futures-io v0.3.24 -> v0.3.25
futures-sink v0.3.24 -> v0.3.25
futures-task v0.3.24 -> v0.3.25
futures-util v0.3.24 -> v0.3.25
getrandom v0.2.7 -> v0.2.8
itoa v1.0.3 -> v1.0.4
libc v0.2.133 -> v0.2.137
mockall v0.11.2 -> v0.11.3
mockall_derive v0.11.2 -> v0.11.3
notify-rust v4.5.9 -> v4.5.10
ntapi v0.3.7 -> v0.4.0
once_cell v1.15.0 -> v1.16.0
os_str_bytes v6.3.0 -> v6.3.1
parking_lot_core v0.9.3 -> v0.9.4
pkg-config …

chore: Upgrade dependencies

---

src/keepassxc/messages/primitives.rs
src/main.rs
src/utils/socket.rs

[1] https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
No.

style: Inline format!() arguments

---

src/cli.rs
src/git.rs
src/keepassxc.rs
src/keepassxc/messages/structs.rs
src/main.rs

Filter login entries by group names provided by --group option. This
option can be repeated.
Since the store operation consists of getting existing entries then
update or create an entry, this option also applies to store. One minor
difference from get is that when a new entry is created, --group options
at the global position are ignored, i.e. it uses the first local --group
option if it's present, or the dedicated group created by
git-credential-keepassxc configure.
Also a new --git-groups option is added to filter login entries using
the names of the dedicated groups. Note that it filters all entries by
all groups from all databases, which can lead to unexpected results if a
user has more than one databases with different dedicated group names.
This is a limitation from KeePassXC as we …

Group filter `--group` and `--git-groups`

---

src/cli.rs
src/main.rs

In [1] the local --group option was used for this purpose. However this
can be somewhat confusing. So adding a separate option and make
--group's behaviour consistent across different subcommands.
[1] https://github.com/Frederick888/git-credential-keepassxc/commit/d33e1ec8e627d24a52dee85e939b40d0c43c4967
No. `--group` has not been released yet.

feat(store): Add `--create-in` option

---

Cargo.lock
Cargo.toml
src/cli.rs
src/keepassxc.rs
src/keepassxc/messages/structs.rs
src/main.rs

By default it lists the groups using tabwriter [1]. Option --raw is
still available.
This is added mainly because I plan to allow UUIDs as --group values.
[1] https://crates.io/crates/tabwriter
No

Implement `groups` subcommand

---

Cargo.lock
Cargo.toml
src/config.rs
src/utils.rs
src/utils/base64.rs

aho-corasick v0.7.19 -> v0.7.20
anyhow v1.0.66 -> v1.0.68
async-broadcast v0.4.1 -> v0.5.0
async-executor v1.4.1 -> v1.5.0
async-io v1.10.0 -> v1.12.0
async-recursion v0.3.2 -> v1.0.2
async-trait v0.1.58 -> v0.1.63
cc v1.0.74 -> v1.0.79
concurrent-queue v1.2.4 -> v2.1.0
crossbeam-epoch v0.9.11 -> v0.9.13
crossbeam-utils v0.8.12 -> v0.8.14
digest v0.10.5 -> v0.10.6
either v1.8.0 -> v1.8.1
indexmap v1.9.1 -> v1.9.2
itoa v1.0.4 -> v1.0.5
libc v0.2.137 -> v0.2.139
notify-rust v4.5.10 -> v4.7.0
num_cpus v1.13.1 -> v1.15.0
num_enum v0.5.7 -> v0.5.9
num_enum_derive v0.5.7 -> v0.5.9
once_cell v1.16.0 -> v1.17.0
ordered-stream v0.0.1 -> v0.1.3
os_str_bytes v6.3.1 -> v6.4.1
parking_lot_core v0.9.4 -> v0.9.6
polling v2.4.0 -> v2.5.2
ppv-lite86 v0.2.16 -> v0.2.17
predicates v2.1.1 -> v2.1.5 …

Upgrade dependencies

---

Cargo.lock
Cargo.toml

anyhow v1.0.68 -> v1.0.69
async-broadcast v0.5.0 -> v0.5.1
async-trait v0.1.63 -> v0.1.64
fastrand v1.8.0 -> v1.9.0
futures-core v0.3.25 -> v0.3.26
futures-io v0.3.25 -> v0.3.26
futures-sink v0.3.25 -> v0.3.26
futures-task v0.3.25 -> v0.3.26
futures-util v0.3.25 -> v0.3.26
heck v0.4.0 -> v0.4.1
notify-rust v4.7.0 -> v4.8.0
num_enum v0.5.9 -> v0.5.11
num_enum_derive v0.5.9 -> v0.5.11
once_cell v1.17.0 -> v1.17.1
ordered-stream v0.1.3 -> v0.2.0
proc-macro2 v1.0.50 -> v1.0.51
serde_json v1.0.91 -> v1.0.93
slab v0.4.7 -> v0.4.8
syn v1.0.107 -> v1.0.109
tempfile v3.3.0 -> v3.4.0
thread_local v1.1.4 -> v1.1.7
time v0.3.17 -> v0.3.20
time-macros v0.2.6 -> v0.2.8
unicode-segmentation v1.10.0 -> v1.10.1
zbus v3.7.0 -> v3.10.0
zbus_macros v3.7.0 -> v3.10.0
zvariant v3.10.0 -> v3.11.0 …

Upgrade deps

---

.github/workflows/gh-ph.yml
.github/workflows/repo-sync.yml

So that when it runs on a PR from a fork, whose owner doesn't have write
access to this repository, can still use this Action.
GitHub user 'wei' does not exist any more.
No

ci: Define gh-ph permissions

---

src/main.rs
src/utils/socket.rs

[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_raw_string_hashes
No

fix: Wrong strict-caller log when skipping caller verification

---

README.md

docs: Add a line about enabling browser integration

---

src/cli.rs

feat: Show build type (debug/release) in --version

---

.github/workflows/repo-sync.yml

This reverts commit cf0301e300b28e755494bcacc28c9d0fb79cc8e7.
[1] https://github.com/wei/git-sync/pull/37
No

Fix GitLab sync

---

.github/workflows/gh-ph.yml
.github/workflows/release.yml
.github/workflows/rust.yml

[1] https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
No

ci: Bump actions to Node 20

---

Justfile
src/config.rs
src/utils/callers.rs

They only happen in tests. It's too much of an overkill to add not(test)
to fix them.
It's only actually read when 'notification' feature is enabled, but I'll
need a bunch of conditional compilation stuff in tests too if I do a
cfg() here, which is not worth it.
No

Fix clippy issues

---

src/main.rs

[1] https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
No

style: Replace map_or() with is_some_and()
